<a href="https://colab.research.google.com/github/laibashaheeen/data_analysis/blob/main/python_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Library

In [1]:
import numpy as np

In [2]:
print(" Python list")
lst = [1,2,3]
lst

 Python list


[1, 2, 3]

In [3]:
print("1D array using numpy")
a = np.array([1,2,3])
print(a)

1D array using numpy
[1 2 3]


In [4]:
print("2D array using numpy aka array of array/s")
b = np.array([
    [1,2,3],[4,5,6]
    ])
print(b)
print ("-----------------------")
c = np.array([
    [1,2,3],[4,5,6],[10,11,12]
    ])
print(c)

2D array using numpy aka array of array/s
[[1 2 3]
 [4 5 6]]
-----------------------
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


In [5]:
print("3D array using numpy aka array of array of array/s")
d = np.array([[[
    1,2,3],[4,5,6],[7,8,9]
               ]])
print(d)

3D array using numpy aka array of array of array/s
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
type(a)

numpy.ndarray

In [7]:
print("Transpose")
b.transpose()
print("------------------------")
d.transpose()

Transpose
------------------------


array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [8]:
print(d.transpose())
b.size

[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]


6

In [9]:
print("np.empty(tuple, dtype)")
np.empty((4,4),dtype=int)       # random no.s in the array

np.empty(tuple, dtype)


array([[   416478051,            0, 489626271861, 433791696995],
       [498216206368, 468151435365, 476741369968, 416611827826],
       [450971566194, 519691042924, 502511173664, 416611827822],
       [416611827830, 463856468073, 420906795105, 433791697004]])

In [10]:
print("np.ones(tuple, dtype)")
np.ones((3,4),dtype=int)    # all ones in the array

np.ones(tuple, dtype)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
np.ones((4,8),dtype=bool)    # boolian value of ones

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [12]:
print("np.zeros(tuple, dtype)")
np.zeros((4,8),dtype=int)    # all zeros in the array

np.zeros(tuple, dtype)


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
np.zeros((4,8),dtype=bool)    # boolian value of zeroes

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [14]:
n = np.arange(1,21)    # generates array which dtarts from 1 ends at 20, default increment by 1
print(n)
n = n.reshape(4,5)     # shaped into 4*5 matrix
print(n)
n = n.flatten()        # inverse of reshape function
print(n)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# Pandas Library

In [15]:
import pandas as pd

In [ ]:
lst = [1,2,3,4,5,6]
lst

[1, 2, 3, 4, 5, 6]

In [16]:
series = pd.Series(lst)
series

0    1
1    2
2    3
dtype: int64

In [17]:
print(type(series))

<class 'pandas.core.series.Series'>


In [18]:
a = pd.Series(['p','q','r','s'], index = [10,11,12, 13])
a

10    p
11    q
12    r
13    s
dtype: object

In [19]:
b = pd.Series([1, 2, 3, 4], index = ['p','q','r','s'])
print(b)

p    1
q    2
r    3
s    4
dtype: int64


In [20]:
print("series")
a = pd.Series(['p','q','r','s'], index = [10,11,12, 13], name= "alphabets")
a

series


10    p
11    q
12    r
13    s
Name: alphabets, dtype: object

In [21]:
print("Scalar series")
scalar_series = pd.Series(0.5, index = [1,2,3,4,5])
scalar_series

Scalar series


1    0.5
2    0.5
3    0.5
4    0.5
5    0.5
dtype: float64

In [22]:
print("Dictionary series")
dict_series = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': '5'})
dict_series

Dictionary series


a    1
b    2
c    3
d    4
e    5
dtype: object

In [23]:
# print(f"Max value: {max(dict_series.astype(int))}")
max(dict_series.astype(int))

5

In [24]:
dict_series[0]

/tmp/ipython-input-1198263229.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dict_series[0]


1

In [25]:
dict_series[0:3]

a    1
b    2
c    3
dtype: object

In [26]:
print("Dictionary series with more columns")
dict_series = pd.Series({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [2, 6, 7],
    'd': [4, 9, 0],
    'e': [1, 7, 9]
    })
dict_series

Dictionary series with more columns


a    [1, 2, 3]
b    [4, 5, 6]
c    [2, 6, 7]
d    [4, 9, 0]
e    [1, 7, 9]
dtype: object

In [27]:
dict_series[0]  # prints row of 0 index

/tmp/ipython-input-1815183288.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dict_series[0]  # prints row of 0 index


[1, 2, 3]

In [28]:
dict_series['c'] # print row of 'c' label

[2, 6, 7]

In [29]:
df = pd.DataFrame(dict_series.tolist(), index= dict_series.index)  #Converts dictionary into a dataframe(table) creats a column for each key
df
print(df[[0,1]])  # prints 1st and 2nd column

print(' '.center(50, '-'))
print(df[0:1])  # prints 1st row

print(' '.center(50, '-'))
print(df[2]) # prints third column

   0  1
a  1  2
b  4  5
c  2  6
d  4  9
e  1  7
------------------------ -------------------------
   0  1  2
a  1  2  3
------------------------ -------------------------
a    3
b    6
c    7
d    0
e    9
Name: 2, dtype: int64


In [30]:
df = pd.read_csv('sample.csv')
df.head()

Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [31]:
df.isnull()

Roll No.  Physics  Chemistry  Maths  Computer
0      False    False      False  False     False
1      False    False      False  False     False
2      False    False      False  False     False
3      False    False      False  False     False
4      False    False      False  False     False
5      False    False       True  False     False
6      False    False      False  False     False
7      False    False      False  False     False
8      False     True      False  False     False
9      False    False      False  False     False
10     False     True      False  False     False
11     False    False       True  False     False
12     False    False      False  False     False
13     False    False       True   True     False
14     False     True      False  False     False
15     False    False      False  False     False
16     False    False      False  False     False
17     False    False      False  False     False
18     False    False      False  False     False
19     False    False      False  False     False
20     False    False      False  False     False
21     False    False      False  False     False
22     False    False      False  False     False
23     False    False      False  False     False
24     False    False       True   True     False
25     False    False      False  False     False
26     False    False      False  False     False
27     False    False      False  False      True
28     False    False      False  False     False
29     False    False      False  False     False

In [32]:
df.isnull().sum()

Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64

In [33]:
df.isnull().sum().sum()

np.int64(10)

In [34]:
df2 = df.dropna()        # drop rows with NaN and saved new dataframe to df2
# df2 = df.dropna(axis = 0)          #drop rows
# df2 = df.dropna(axis = 1)          #drop columns
df2.shape

(22, 5)

In [35]:
df3 = df.fillna(0)   # fills 0 where null value is found
df3.head(12)

Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        0.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      0.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      0.0       17.0   18.0      19.0
11        12     88.0        0.0   19.0      20.0

In [36]:
df3 = df.fillna(method = 'ffill')      # fills previous value of same column by default (same as axis = 0)
df3.head(12)


/tmp/ipython-input-566572548.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3 = df.fillna(method = 'ffill')      # fills previous value of same column by default (same as axis = 0)


Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0       27.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9     78.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11     45.0       17.0   18.0      19.0
11        12     88.0       17.0   19.0      20.0

In [37]:
df3 = df.fillna(method = 'ffill', axis = 1)      # prints previous value from row
df3.head(12)


/tmp/ipython-input-355565816.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3 = df.fillna(method = 'ffill', axis = 1)      # prints previous value from row


Roll No.  Physics  Chemistry  Maths  Computer
0        1.0     56.0       57.0   58.0      59.0
1        2.0     23.0       24.0   25.0      26.0
2        3.0     89.0       25.0   26.0      27.0
3        4.0     45.0       26.0   27.0      28.0
4        5.0     23.0       27.0   28.0      29.0
5        6.0     90.0       90.0   29.0      30.0
6        7.0     12.0       13.0   14.0      15.0
7        8.0     78.0       14.0   15.0      16.0
8        9.0      9.0       15.0   16.0      17.0
9       10.0     45.0       16.0   17.0      18.0
10      11.0     11.0       17.0   18.0      19.0
11      12.0     88.0       88.0   19.0      20.0

In [38]:
df3['Physics'] = df['Physics'].fillna(value= df['Physics'].mean())
df3.head(20)

Roll No.    Physics  Chemistry  Maths  Computer
0        1.0  56.000000       57.0   58.0      59.0
1        2.0  23.000000       24.0   25.0      26.0
2        3.0  89.000000       25.0   26.0      27.0
3        4.0  45.000000       26.0   27.0      28.0
4        5.0  23.000000       27.0   28.0      29.0
5        6.0  90.000000       90.0   29.0      30.0
6        7.0  12.000000       13.0   14.0      15.0
7        8.0  78.000000       14.0   15.0      16.0
8        9.0  52.814815       15.0   16.0      17.0
9       10.0  45.000000       16.0   17.0      18.0
10      11.0  52.814815       17.0   18.0      19.0
11      12.0  88.000000       88.0   19.0      20.0
12      13.0  22.000000       23.0   24.0      25.0
13      14.0  90.000000       90.0   90.0      42.0
14      15.0  52.814815       43.0   43.0      43.0
15      16.0  44.000000       44.0   44.0      44.0
16      17.0  45.000000       45.0   45.0      45.0
17      18.0  46.000000       46.0   46.0      46.0
18      19.0  47.000000       47.0   47.0      47.0
19      20.0  48.000000       48.0   48.0      48.0

In [39]:
df3 = df.replace(24, 1000)       # replace 24 by 1000
df3.head()

Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0     1000.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [40]:
data = pd.read_csv('sample2.csv', index_col = 'Roll No.')
data.head()

Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.                                                                
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001
2              A    ECE     23.0       24.0   25.0      26.0  02-01-2001
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [41]:
data.loc[1]   # loc by 1st row

Section               A
Branch               CS
Physics            56.0
Chemistry          57.0
Maths              58.0
Computer           59.0
DOB          01-01-2001
Name: 1, dtype: object

In [42]:
data.loc[5,'Physics']     # loc of value of pysics at 5th roll no.

np.float64(23.0)

In [43]:
data.loc[data['Physics']<50]

Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.                                                                
2              A    ECE     23.0       24.0   25.0      26.0  02-01-2001
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001
7              B     CS     12.0       13.0   14.0      15.0  07-01-2001
10             A     CS     45.0       16.0   17.0      18.0  10-01-2001
13             A     CS     22.0       23.0   24.0      25.0  13-01-2001
16             C    NaN     44.0       44.0   44.0      44.0  16-01-2001
17             A   MECH     45.0       45.0   45.0      45.0  17-01-2001
18             A   MECH     46.0       46.0   46.0      46.0  18-01-2001
19             B    ECE     47.0       47.0   47.0      47.0  19-01-2001
20             C   MECH     48.0       48.0   48.0      48.0  20-01-2001
21             A   MECH     49.0       49.0   49.0      49.0  21-01-2001

In [44]:
data.loc[data['Physics']>80, ['Physics','Maths']]

Physics  Maths
Roll No.                
3            89.0   26.0
6            90.0   29.0
12           88.0   19.0
14           90.0    NaN

Append / Concat

In [76]:
df1 = pd.DataFrame({
    'Roll No.': [1, 2, 3, 4, 5],
    'Maths': [45, 78, 45, 90, 66],
    'Physics': [33, 67, 12, 90, 44]
})

df2 = pd.DataFrame({
    'Roll No.': [6, 7, 8, 9, 10],
    'Maths': [78, 73, 45, 90, 69],
    'Physics': [23, 67, 88, 0, 98]
})

print(df1)
print(df2)

   Roll No.  Maths  Physics
0         1     45       33
1         2     78       67
2         3     45       12
3         4     90       90
4         5     66       44
   Roll No.  Maths  Physics
0         6     78       23
1         7     73       67
2         8     45       88
3         9     90        0
4        10     69       98


In [77]:
pd.concat([df1, df2])

Roll No.  Maths  Physics
0         1     45       33
1         2     78       67
2         3     45       12
3         4     90       90
4         5     66       44
0         6     78       23
1         7     73       67
2         8     45       88
3         9     90        0
4        10     69       98

In [79]:
pd.concat([df1, df2], ignore_index=True)

Roll No.  Maths  Physics
0         1     45       33
1         2     78       67
2         3     45       12
3         4     90       90
4         5     66       44
5         6     78       23
6         7     73       67
7         8     45       88
8         9     90        0
9        10     69       98

Group by()

In [53]:
Branch_group = data.groupby(by = ['Branch', 'Section'])

In [54]:
Branch_group.groups

{('CS', 'A'): [1, 5, 10, 13, 14, 29, 30], ('CS', 'B'): [7, 27], ('CS', 'C'): [12, 28], ('ECE', 'A'): [2, 6, 9, 26], ('ECE', 'B'): [11, 15, 19, 23], ('MECH', 'A'): [17, 18, 21, 22, 25], ('MECH', 'B'): [3], ('MECH', 'C'): [4, 20, 24], (nan, 'C'): [8, 16]}

In [55]:
for branch , group in Branch_group:
    print(branch)
    print(group)
    print(' '.center(50, '-'))

('CS', 'A')
         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.                                                                
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001
10             A     CS     45.0       16.0   17.0      18.0  10-01-2001
13             A     CS     22.0       23.0   24.0      25.0  13-01-2001
14             A     CS     90.0        NaN    NaN      42.0  14-01-2001
29             A     CS     57.0       36.0   36.0      66.0  29-01-2001
30             A     CS     58.0       37.0   37.0      43.0  30-01-2001
------------------------ -------------------------
('CS', 'B')
         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.                                                                
7              B     CS     12.0       13.0   14.0      15.0  07-01-2001
27             B     CS     55.0       34.0   34.

Merge()

In [64]:
data1 = pd.DataFrame({
    'Roll No.': [1, 2, 3, 4, 5],
    'Maths': [45, 78, 45, 90, 66]})
print(data1)
data2 =  pd.DataFrame({
    'Roll No.': [1, 2, 3, 4, 5],
    'Physics': [56, 78, 23, 90, 34]})
print(data2)

   Roll No.  Maths
0         1     45
1         2     78
2         3     45
3         4     90
4         5     66
   Roll No.  Physics
0         1       56
1         2       78
2         3       23
3         4       90
4         5       34


In [61]:
merged_data = pd.merge(data1, data2, on = 'Roll No.')
merged_data

Roll No.  Maths  Physics
0         1     45       56
1         2     78       78
2         3     45       23
3         4     90       90
4         5     66       34

In [65]:
data3 = pd.DataFrame({
    'Roll No.': [1, 2, 3, 4, 5],
    'Maths': [45, 78, 45, 90, 66]})
print(data3)
data4 =  pd.DataFrame({
    'Roll No.': [1, 2, 3, 7,8],
    'Physics': [56, 78, 23, 90, 34]})
print(data4)

   Roll No.  Maths
0         1     45
1         2     78
2         3     45
3         4     90
4         5     66
   Roll No.  Physics
0         1       56
1         2       78
2         3       23
3         7       90
4         8       34


In [66]:
merged_data = pd.merge(data3, data4)
merged_data

Roll No.  Maths  Physics
0         1     45       56
1         2     78       78
2         3     45       23

In [68]:
merged_data = pd.merge(data3, data4, how = 'left')
merged_data

Roll No.  Maths  Physics
0         1     45     56.0
1         2     78     78.0
2         3     45     23.0
3         4     90      NaN
4         5     66      NaN

In [69]:
merged_data = pd.merge(data3, data4, how = 'right')
merged_data

Roll No.  Maths  Physics
0         1   45.0       56
1         2   78.0       78
2         3   45.0       23
3         7    NaN       90
4         8    NaN       34

In [70]:
merged_data = pd.merge(data3, data4, how = 'outer')
merged_data

Roll No.  Maths  Physics
0         1   45.0     56.0
1         2   78.0     78.0
2         3   45.0     23.0
3         4   90.0      NaN
4         5   66.0      NaN
5         7    NaN     90.0
6         8    NaN     34.0